language: r
cache: packages
r:
  - release
  - devel
warnings_are_errors: true
notifications:
  email: false

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls(type="all", combine_types=TRUE)'
